# Generated by Django 3.1.1 on 2020-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200922_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websitedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(default='ชื่อเว็บไซต์', max_length=200, unique=True)),
                ('websitedetail', models.CharField(default='รายละเอียดเว็บไซต์', max_length=400, unique=True)),
            ],
        ),
    ]
